targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generates config for all environments
          # Omit this line if you want to generate for specific environments

