// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:rideglory/core/config/app_env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _value(String? enviedValue, String dartDefineKey) {
    return enviedValue ?? String.fromEnvironment(dartDefineKey);
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _value(AppEnv.firebaseAndroidApiKey, 'FIREBASE_ANDROID_API_KEY'),
    appId: _value(AppEnv.firebaseAndroidAppId, 'FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: _value(
      AppEnv.firebaseMessagingSenderId,
      'FIREBASE_MESSAGING_SENDER_ID',
    ),
    projectId: _value(AppEnv.firebaseProjectId, 'FIREBASE_PROJECT_ID'),
    storageBucket: _value(
      AppEnv.firebaseStorageBucket,
      'FIREBASE_STORAGE_BUCKET',
    ),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _value(AppEnv.firebaseIosApiKey, 'FIREBASE_IOS_API_KEY'),
    appId: _value(AppEnv.firebaseIosAppId, 'FIREBASE_IOS_APP_ID'),
    messagingSenderId: _value(
      AppEnv.firebaseMessagingSenderId,
      'FIREBASE_MESSAGING_SENDER_ID',
    ),
    projectId: _value(AppEnv.firebaseProjectId, 'FIREBASE_PROJECT_ID'),
    storageBucket: _value(
      AppEnv.firebaseStorageBucket,
      'FIREBASE_STORAGE_BUCKET',
    ),
    androidClientId: _value(
      AppEnv.firebaseAndroidClientId,
      'FIREBASE_ANDROID_CLIENT_ID',
    ),
    iosClientId: _value(AppEnv.firebaseIosClientId, 'FIREBASE_IOS_CLIENT_ID'),
    iosBundleId: _value(AppEnv.firebaseIosBundleId, 'FIREBASE_IOS_BUNDLE_ID'),
  );
}
